language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mhumpert/k8s-complex-app-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mhumpert/k8s-complex-app-client-test npm test

after_success:
  # Be aware that you must use your docker hub username in the image tag
  # in the format <docker hub username>/<image-tag-name>
  # in order to successfully upload it to docker hub in the next step!
  - docker build -t mhumpert/k8s-complex-app-client ./client
  - docker build -t mhumpert/k8s-complex-app-api ./api
  - docker build -t mhumpert/k8s-complex-app-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mhumpert/k8s-complex-app-client
  - docker push mhumpert/k8s-complex-app-api
  - docker push mhumpert/k8s-complex-app-worker